// Mocks generated by Mockito 5.4.6 from annotations
// in sharezone/test/account/select_state_dialog_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:holidays/holidays.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sharezone/holidays/holiday_bloc.dart' as _i3;
import 'package:user/user.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeHolidayService_0 extends _i1.SmartFake
    implements _i2.HolidayService {
  _FakeHolidayService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHolidayStateGateway_1 extends _i1.SmartFake
    implements _i3.HolidayStateGateway {
  _FakeHolidayStateGateway_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HolidayBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockHolidayBloc extends _i1.Mock implements _i3.HolidayBloc {
  @override
  _i2.HolidayService get holidayManager =>
      (super.noSuchMethod(
            Invocation.getter(#holidayManager),
            returnValue: _FakeHolidayService_0(
              this,
              Invocation.getter(#holidayManager),
            ),
            returnValueForMissingStub: _FakeHolidayService_0(
              this,
              Invocation.getter(#holidayManager),
            ),
          )
          as _i2.HolidayService);

  @override
  _i4.Stream<List<_i2.Holiday?>> get holidays =>
      (super.noSuchMethod(
            Invocation.getter(#holidays),
            returnValue: _i4.Stream<List<_i2.Holiday?>>.empty(),
            returnValueForMissingStub: _i4.Stream<List<_i2.Holiday?>>.empty(),
          )
          as _i4.Stream<List<_i2.Holiday?>>);

  @override
  _i3.HolidayStateGateway get stateGateway =>
      (super.noSuchMethod(
            Invocation.getter(#stateGateway),
            returnValue: _FakeHolidayStateGateway_1(
              this,
              Invocation.getter(#stateGateway),
            ),
            returnValueForMissingStub: _FakeHolidayStateGateway_1(
              this,
              Invocation.getter(#stateGateway),
            ),
          )
          as _i3.HolidayStateGateway);

  @override
  _i4.Stream<_i5.StateEnum?> get userState =>
      (super.noSuchMethod(
            Invocation.getter(#userState),
            returnValue: _i4.Stream<_i5.StateEnum?>.empty(),
            returnValueForMissingStub: _i4.Stream<_i5.StateEnum?>.empty(),
          )
          as _i4.Stream<_i5.StateEnum?>);

  @override
  _i4.Stream<bool> get hasStateSelected =>
      (super.noSuchMethod(
            Invocation.getter(#hasStateSelected),
            returnValue: _i4.Stream<bool>.empty(),
            returnValueForMissingStub: _i4.Stream<bool>.empty(),
          )
          as _i4.Stream<bool>);

  @override
  _i4.Future<void> Function(_i5.StateEnum?) get changeState =>
      (super.noSuchMethod(
            Invocation.getter(#changeState),
            returnValue: (_i5.StateEnum? state) => _i4.Future<void>.value(),
            returnValueForMissingStub:
                (_i5.StateEnum? state) => _i4.Future<void>.value(),
          )
          as _i4.Future<void> Function(_i5.StateEnum?));

  @override
  set getCurrentTime(DateTime Function()? value) => super.noSuchMethod(
    Invocation.setter(#getCurrentTime, value),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
