// Mocks generated by Mockito 5.4.6 from annotations
// in sharezone/test/grades/pages/grades_dialog/grades_dialog_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:analytics/analytics.dart' as _i6;
import 'package:crash_analytics/crash_analytics.dart' as _i3;
import 'package:flutter/foundation.dart' as _i5;
import 'package:flutter/material.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:sharezone/grades/pages/grades_dialog/grades_dialog_controller.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeBuildContext_0 extends _i1.SmartFake implements _i2.BuildContext {
  _FakeBuildContext_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CrashAnalytics].
///
/// See the documentation for Mockito's code generation for more information.
class MockCrashAnalytics extends _i1.Mock implements _i3.CrashAnalytics {
  @override
  set enableInDevMode(bool? value) => super.noSuchMethod(
    Invocation.setter(#enableInDevMode, value),
    returnValueForMissingStub: null,
  );

  @override
  void crash() => super.noSuchMethod(
    Invocation.method(#crash, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> recordFlutterError(_i5.FlutterErrorDetails? details) =>
      (super.noSuchMethod(
            Invocation.method(#recordFlutterError, [details]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> recordError(
    dynamic exception,
    StackTrace? stack, {
    bool? fatal = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #recordError,
              [exception, stack],
              {#fatal: fatal},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void log(String? msg) => super.noSuchMethod(
    Invocation.method(#log, [msg]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> setCustomKey(String? key, dynamic value) =>
      (super.noSuchMethod(
            Invocation.method(#setCustomKey, [key, value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setUserIdentifier(String? identifier) =>
      (super.noSuchMethod(
            Invocation.method(#setUserIdentifier, [identifier]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setCrashAnalyticsEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setCrashAnalyticsEnabled, [enabled]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [Analytics].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalytics extends _i1.Mock implements _i6.Analytics {
  @override
  void log(_i6.AnalyticsEvent? event) => super.noSuchMethod(
    Invocation.method(#log, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void setAnalyticsCollectionEnabled(bool? value) => super.noSuchMethod(
    Invocation.method(#setAnalyticsCollectionEnabled, [value]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> logSignUp({required String? signUpMethod}) =>
      (super.noSuchMethod(
            Invocation.method(#logSignUp, [], {#signUpMethod: signUpMethod}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setCurrentScreen({required String? screenName}) =>
      (super.noSuchMethod(
            Invocation.method(#setCurrentScreen, [], {#screenName: screenName}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setUserProperty({
    required String? name,
    required String? value,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setUserProperty, [], {
              #name: name,
              #value: value,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [GradesDialogControllerTranslations].
///
/// See the documentation for Mockito's code generation for more information.
class MockGradesDialogControllerTranslations extends _i1.Mock
    implements _i7.GradesDialogControllerTranslations {
  @override
  _i2.BuildContext get context =>
      (super.noSuchMethod(
            Invocation.getter(#context),
            returnValue: _FakeBuildContext_0(this, Invocation.getter(#context)),
            returnValueForMissingStub: _FakeBuildContext_0(
              this,
              Invocation.getter(#context),
            ),
          )
          as _i2.BuildContext);

  @override
  String get enterGradeError =>
      (super.noSuchMethod(
            Invocation.getter(#enterGradeError),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#enterGradeError),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#enterGradeError),
            ),
          )
          as String);

  @override
  String get gradeIsInvalidError =>
      (super.noSuchMethod(
            Invocation.getter(#gradeIsInvalidError),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#gradeIsInvalidError),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#gradeIsInvalidError),
            ),
          )
          as String);

  @override
  String get gradeIsOutOfRangeError =>
      (super.noSuchMethod(
            Invocation.getter(#gradeIsOutOfRangeError),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#gradeIsOutOfRangeError),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#gradeIsOutOfRangeError),
            ),
          )
          as String);

  @override
  String get enterTitleError =>
      (super.noSuchMethod(
            Invocation.getter(#enterTitleError),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#enterTitleError),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#enterTitleError),
            ),
          )
          as String);

  @override
  String get gradeInvalid =>
      (super.noSuchMethod(
            Invocation.getter(#gradeInvalid),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#gradeInvalid),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#gradeInvalid),
            ),
          )
          as String);
}
