// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8-b8Y3FgGA90Lr41pZqgR-dW5z1JqHBA',
    appId: '1:730263787697:web:760f039d3f7a773b6c6a90',
    messagingSenderId: '730263787697',
    projectId: 'sharezone-c2bd8',
    authDomain: 'sharezone-c2bd8.firebaseapp.com',
    databaseURL: 'https://sharezone-c2bd8.firebaseio.com',
    storageBucket: 'sharezone-c2bd8.appspot.com',
    measurementId: 'G-1SDEC1XMTB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_vFdcAexcO38jtzkW_MK_LWWx4X9tJ2k',
    appId: '1:730263787697:android:f0a3b3b856fd1383',
    messagingSenderId: '730263787697',
    projectId: 'sharezone-c2bd8',
    databaseURL: 'https://sharezone-c2bd8.firebaseio.com',
    storageBucket: 'sharezone-c2bd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2VFGw3_SP11Ovuy3NDx7ZXAHiHtAoGGk',
    appId: '1:730263787697:ios:3ff9b2cb1c2a5a31',
    messagingSenderId: '730263787697',
    projectId: 'sharezone-c2bd8',
    databaseURL: 'https://sharezone-c2bd8.firebaseio.com',
    storageBucket: 'sharezone-c2bd8.appspot.com',
    androidClientId:
        '730263787697-3k362gt3s1lu4d2entj682com1a42ud1.apps.googleusercontent.com',
    iosClientId:
        '730263787697-r3ubdsbn4l752elbpnh6nu2tpiqq439p.apps.googleusercontent.com',
    iosBundleId: 'de.codingbrain.sharezone.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2VFGw3_SP11Ovuy3NDx7ZXAHiHtAoGGk',
    appId: '1:730263787697:ios:3ff9b2cb1c2a5a31',
    messagingSenderId: '730263787697',
    projectId: 'sharezone-c2bd8',
    databaseURL: 'https://sharezone-c2bd8.firebaseio.com',
    storageBucket: 'sharezone-c2bd8.appspot.com',
    androidClientId:
        '730263787697-3k362gt3s1lu4d2entj682com1a42ud1.apps.googleusercontent.com',
    iosClientId:
        '730263787697-r3ubdsbn4l752elbpnh6nu2tpiqq439p.apps.googleusercontent.com',
    iosBundleId: 'de.codingbrain.sharezone.app',
  );
}
