// Mocks generated by Mockito 5.4.4 from annotations
// in sharezone/test_goldens/groups/src/pages/course/create/course_template_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i8;

import 'package:common_domain_models/common_domain_models.dart' as _i5;
import 'package:group_domain_models/group_domain_models.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:sharezone/groups/src/pages/course/create/bloc/course_create_bloc.dart'
    as _i2;
import 'package:sharezone/groups/src/pages/course/create/bloc/course_create_bloc_factory.dart'
    as _i6;
import 'package:sharezone/groups/src/pages/course/create/bloc/my_admin_school_classes_provider.dart'
    as _i7;
import 'package:sharezone/groups/src/pages/course/create/models/course_template.dart'
    as _i10;
import 'package:sharezone/util/api/connections_gateway.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCourseCreateBloc_0 extends _i1.SmartFake
    implements _i2.CourseCreateBloc {
  _FakeCourseCreateBloc_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConnectionsGateway_1 extends _i1.SmartFake
    implements _i3.ConnectionsGateway {
  _FakeConnectionsGateway_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamTransformer_2<S, T> extends _i1.SmartFake
    implements _i4.StreamTransformer<S, T> {
  _FakeStreamTransformer_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCourseId_3 extends _i1.SmartFake implements _i5.CourseId {
  _FakeCourseId_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CourseCreateBlocFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockCourseCreateBlocFactory extends _i1.Mock
    implements _i6.CourseCreateBlocFactory {
  @override
  _i2.CourseCreateBloc create({_i5.SchoolClassId? schoolClassId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [],
          {#schoolClassId: schoolClassId},
        ),
        returnValue: _FakeCourseCreateBloc_0(
          this,
          Invocation.method(
            #create,
            [],
            {#schoolClassId: schoolClassId},
          ),
        ),
        returnValueForMissingStub: _FakeCourseCreateBloc_0(
          this,
          Invocation.method(
            #create,
            [],
            {#schoolClassId: schoolClassId},
          ),
        ),
      ) as _i2.CourseCreateBloc);
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [MyAdminSchoolClassesProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockMyAdminSchoolClassesProvider extends _i1.Mock
    implements _i7.MyAdminSchoolClassesProvider {
  @override
  _i3.ConnectionsGateway get connectionsGateway => (super.noSuchMethod(
        Invocation.getter(#connectionsGateway),
        returnValue: _FakeConnectionsGateway_1(
          this,
          Invocation.getter(#connectionsGateway),
        ),
        returnValueForMissingStub: _FakeConnectionsGateway_1(
          this,
          Invocation.getter(#connectionsGateway),
        ),
      ) as _i3.ConnectionsGateway);
  @override
  List<(_i5.SchoolClassId, String)> get schoolClasses => (super.noSuchMethod(
        Invocation.getter(#schoolClasses),
        returnValue: <(_i5.SchoolClassId, String)>[],
        returnValueForMissingStub: <(_i5.SchoolClassId, String)>[],
      ) as List<(_i5.SchoolClassId, String)>);
  @override
  set schoolClasses(List<(_i5.SchoolClassId, String)>? _schoolClasses) =>
      super.noSuchMethod(
        Invocation.setter(
          #schoolClasses,
          _schoolClasses,
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  void init() => super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [CourseCreateBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockCourseCreateBloc extends _i1.Mock implements _i2.CourseCreateBloc {
  @override
  set schoolClassId(_i5.SchoolClassId? _schoolClassId) => super.noSuchMethod(
        Invocation.setter(
          #schoolClassId,
          _schoolClassId,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set initialCourse(_i9.Course? _initialCourse) => super.noSuchMethod(
        Invocation.setter(
          #initialCourse,
          _initialCourse,
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool get hasSchoolClassId => (super.noSuchMethod(
        Invocation.getter(#hasSchoolClassId),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  _i4.Stream<String> get subject => (super.noSuchMethod(
        Invocation.getter(#subject),
        returnValue: _i4.Stream<String>.empty(),
        returnValueForMissingStub: _i4.Stream<String>.empty(),
      ) as _i4.Stream<String>);
  @override
  dynamic Function(String) get changeName => (super.noSuchMethod(
        Invocation.getter(#changeName),
        returnValue: (String __p0) => null,
        returnValueForMissingStub: (String __p0) => null,
      ) as dynamic Function(String));
  @override
  dynamic Function(String) get changeSubject => (super.noSuchMethod(
        Invocation.getter(#changeSubject),
        returnValue: (String __p0) => null,
        returnValueForMissingStub: (String __p0) => null,
      ) as dynamic Function(String));
  @override
  dynamic Function(String) get changeAbbreviation => (super.noSuchMethod(
        Invocation.getter(#changeAbbreviation),
        returnValue: (String __p0) => null,
        returnValueForMissingStub: (String __p0) => null,
      ) as dynamic Function(String));
  @override
  _i4.StreamTransformer<String, String> get validateSubject =>
      (super.noSuchMethod(
        Invocation.getter(#validateSubject),
        returnValue: _FakeStreamTransformer_2<String, String>(
          this,
          Invocation.getter(#validateSubject),
        ),
        returnValueForMissingStub: _FakeStreamTransformer_2<String, String>(
          this,
          Invocation.getter(#validateSubject),
        ),
      ) as _i4.StreamTransformer<String, String>);
  @override
  void setInitialTemplate(_i10.CourseTemplate? template) => super.noSuchMethod(
        Invocation.method(
          #setInitialTemplate,
          [template],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void setSchoolClassId(_i5.SchoolClassId? schoolClassId) => super.noSuchMethod(
        Invocation.method(
          #setSchoolClassId,
          [schoolClassId],
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool hasUserEditInput() => (super.noSuchMethod(
        Invocation.method(
          #hasUserEditInput,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  _i4.Future<(_i5.CourseId, String)> submitCourse() => (super.noSuchMethod(
        Invocation.method(
          #submitCourse,
          [],
        ),
        returnValue: _i4.Future<(_i5.CourseId, String)>.value((
          _FakeCourseId_3(
            this,
            Invocation.method(
              #submitCourse,
              [],
            ),
          ),
          _i11.dummyValue<String>(
            this,
            Invocation.method(
              #submitCourse,
              [],
            ),
          )
        )),
        returnValueForMissingStub: _i4.Future<(_i5.CourseId, String)>.value((
          _FakeCourseId_3(
            this,
            Invocation.method(
              #submitCourse,
              [],
            ),
          ),
          _i11.dummyValue<String>(
            this,
            Invocation.method(
              #submitCourse,
              [],
            ),
          )
        )),
      ) as _i4.Future<(_i5.CourseId, String)>);
  @override
  _i4.Future<(_i5.CourseId, String)> submitWithCourseTemplate(
          _i10.CourseTemplate? courseTemplate) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitWithCourseTemplate,
          [courseTemplate],
        ),
        returnValue: _i4.Future<(_i5.CourseId, String)>.value((
          _FakeCourseId_3(
            this,
            Invocation.method(
              #submitWithCourseTemplate,
              [courseTemplate],
            ),
          ),
          _i11.dummyValue<String>(
            this,
            Invocation.method(
              #submitWithCourseTemplate,
              [courseTemplate],
            ),
          )
        )),
        returnValueForMissingStub: _i4.Future<(_i5.CourseId, String)>.value((
          _FakeCourseId_3(
            this,
            Invocation.method(
              #submitWithCourseTemplate,
              [courseTemplate],
            ),
          ),
          _i11.dummyValue<String>(
            this,
            Invocation.method(
              #submitWithCourseTemplate,
              [courseTemplate],
            ),
          )
        )),
      ) as _i4.Future<(_i5.CourseId, String)>);
  @override
  _i4.Future<void> deleteCourse(_i5.CourseId? courseId) => (super.noSuchMethod(
        Invocation.method(
          #deleteCourse,
          [courseId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  bool isCourseTemplateAlreadyAdded(_i10.CourseTemplate? courseTemplate) =>
      (super.noSuchMethod(
        Invocation.method(
          #isCourseTemplateAlreadyAdded,
          [courseTemplate],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
