// Mocks generated by Mockito 5.4.6 from annotations
// in sharezone/test/submissions/submission_permissions_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;

import 'package:app_functions/app_functions.dart' as _i5;
import 'package:common_domain_models/common_domain_models.dart' as _i6;
import 'package:design/design.dart' as _i11;
import 'package:group_domain_models/group_domain_accessors.dart' as _i3;
import 'package:group_domain_models/group_domain_models.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:sharezone/util/api/course_gateway.dart' as _i7;
import 'package:sharezone/util/api/school_class_gateway.dart' as _i12;
import 'package:sharezone/util/api/user_api.dart' as _i9;
import 'package:sharezone_common/references.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeReferences_0 extends _i1.SmartFake implements _i2.References {
  _FakeReferences_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCourseMemberAccessor_1 extends _i1.SmartFake
    implements _i3.CourseMemberAccessor {
  _FakeCourseMemberAccessor_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCourse_2 extends _i1.SmartFake implements _i4.Course {
  _FakeCourse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppFunctionsResult_3<T> extends _i1.SmartFake
    implements _i5.AppFunctionsResult<T> {
  _FakeAppFunctionsResult_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCourseId_4 extends _i1.SmartFake implements _i6.CourseId {
  _FakeCourseId_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CourseGateway].
///
/// See the documentation for Mockito's code generation for more information.
class MockCourseGateway extends _i1.Mock implements _i7.CourseGateway {
  @override
  _i2.References get references =>
      (super.noSuchMethod(
            Invocation.getter(#references),
            returnValue: _FakeReferences_0(
              this,
              Invocation.getter(#references),
            ),
            returnValueForMissingStub: _FakeReferences_0(
              this,
              Invocation.getter(#references),
            ),
          )
          as _i2.References);

  @override
  String get memberID =>
      (super.noSuchMethod(
            Invocation.getter(#memberID),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#memberID),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#memberID),
            ),
          )
          as String);

  @override
  _i3.CourseMemberAccessor get memberAccessor =>
      (super.noSuchMethod(
            Invocation.getter(#memberAccessor),
            returnValue: _FakeCourseMemberAccessor_1(
              this,
              Invocation.getter(#memberAccessor),
            ),
            returnValueForMissingStub: _FakeCourseMemberAccessor_1(
              this,
              Invocation.getter(#memberAccessor),
            ),
          )
          as _i3.CourseMemberAccessor);

  @override
  _i4.Course createCourse(
    _i4.CourseData? courseData,
    _i9.UserGateway? userGateway,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createCourse, [courseData, userGateway]),
            returnValue: _FakeCourse_2(
              this,
              Invocation.method(#createCourse, [courseData, userGateway]),
            ),
            returnValueForMissingStub: _FakeCourse_2(
              this,
              Invocation.method(#createCourse, [courseData, userGateway]),
            ),
          )
          as _i4.Course);

  @override
  _i10.Future<_i5.AppFunctionsResult<bool>> joinCourse(String? courseID) =>
      (super.noSuchMethod(
            Invocation.method(#joinCourse, [courseID]),
            returnValue: _i10.Future<_i5.AppFunctionsResult<bool>>.value(
              _FakeAppFunctionsResult_3<bool>(
                this,
                Invocation.method(#joinCourse, [courseID]),
              ),
            ),
            returnValueForMissingStub:
                _i10.Future<_i5.AppFunctionsResult<bool>>.value(
                  _FakeAppFunctionsResult_3<bool>(
                    this,
                    Invocation.method(#joinCourse, [courseID]),
                  ),
                ),
          )
          as _i10.Future<_i5.AppFunctionsResult<bool>>);

  @override
  _i10.Future<_i5.AppFunctionsResult<bool>> leaveCourse(String? courseID) =>
      (super.noSuchMethod(
            Invocation.method(#leaveCourse, [courseID]),
            returnValue: _i10.Future<_i5.AppFunctionsResult<bool>>.value(
              _FakeAppFunctionsResult_3<bool>(
                this,
                Invocation.method(#leaveCourse, [courseID]),
              ),
            ),
            returnValueForMissingStub:
                _i10.Future<_i5.AppFunctionsResult<bool>>.value(
                  _FakeAppFunctionsResult_3<bool>(
                    this,
                    Invocation.method(#leaveCourse, [courseID]),
                  ),
                ),
          )
          as _i10.Future<_i5.AppFunctionsResult<bool>>);

  @override
  _i10.Future<_i5.AppFunctionsResult<bool>> kickMember(
    String? courseID,
    String? kickedMemberID,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#kickMember, [courseID, kickedMemberID]),
            returnValue: _i10.Future<_i5.AppFunctionsResult<bool>>.value(
              _FakeAppFunctionsResult_3<bool>(
                this,
                Invocation.method(#kickMember, [courseID, kickedMemberID]),
              ),
            ),
            returnValueForMissingStub:
                _i10.Future<_i5.AppFunctionsResult<bool>>.value(
                  _FakeAppFunctionsResult_3<bool>(
                    this,
                    Invocation.method(#kickMember, [courseID, kickedMemberID]),
                  ),
                ),
          )
          as _i10.Future<_i5.AppFunctionsResult<bool>>);

  @override
  _i10.Future<_i5.AppFunctionsResult<bool>> editCourse(_i4.Course? course) =>
      (super.noSuchMethod(
            Invocation.method(#editCourse, [course]),
            returnValue: _i10.Future<_i5.AppFunctionsResult<bool>>.value(
              _FakeAppFunctionsResult_3<bool>(
                this,
                Invocation.method(#editCourse, [course]),
              ),
            ),
            returnValueForMissingStub:
                _i10.Future<_i5.AppFunctionsResult<bool>>.value(
                  _FakeAppFunctionsResult_3<bool>(
                    this,
                    Invocation.method(#editCourse, [course]),
                  ),
                ),
          )
          as _i10.Future<_i5.AppFunctionsResult<bool>>);

  @override
  _i4.Course? getCourse(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCourse, [id]),
            returnValueForMissingStub: null,
          )
          as _i4.Course?);

  @override
  _i10.Future<_i5.AppFunctionsResult<bool>> editCourseSettings(
    String? courseID,
    _i4.CourseSettings? courseSettings,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#editCourseSettings, [courseID, courseSettings]),
            returnValue: _i10.Future<_i5.AppFunctionsResult<bool>>.value(
              _FakeAppFunctionsResult_3<bool>(
                this,
                Invocation.method(#editCourseSettings, [
                  courseID,
                  courseSettings,
                ]),
              ),
            ),
            returnValueForMissingStub:
                _i10.Future<_i5.AppFunctionsResult<bool>>.value(
                  _FakeAppFunctionsResult_3<bool>(
                    this,
                    Invocation.method(#editCourseSettings, [
                      courseID,
                      courseSettings,
                    ]),
                  ),
                ),
          )
          as _i10.Future<_i5.AppFunctionsResult<bool>>);

  @override
  _i10.Future<_i5.AppFunctionsResult<bool>> deleteCourse(String? courseID) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCourse, [courseID]),
            returnValue: _i10.Future<_i5.AppFunctionsResult<bool>>.value(
              _FakeAppFunctionsResult_3<bool>(
                this,
                Invocation.method(#deleteCourse, [courseID]),
              ),
            ),
            returnValueForMissingStub:
                _i10.Future<_i5.AppFunctionsResult<bool>>.value(
                  _FakeAppFunctionsResult_3<bool>(
                    this,
                    Invocation.method(#deleteCourse, [courseID]),
                  ),
                ),
          )
          as _i10.Future<_i5.AppFunctionsResult<bool>>);

  @override
  _i10.Future<bool> editCourseGeneralDesign({
    required String? courseID,
    _i11.Design? design,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#editCourseGeneralDesign, [], {
              #courseID: courseID,
              #design: design,
            }),
            returnValue: _i10.Future<bool>.value(false),
            returnValueForMissingStub: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<bool> editCoursePersonalDesign({
    required String? courseID,
    _i11.Design? personalDesign,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#editCoursePersonalDesign, [], {
              #courseID: courseID,
              #personalDesign: personalDesign,
            }),
            returnValue: _i10.Future<bool>.value(false),
            returnValueForMissingStub: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<bool> removeCoursePersonalDesign(String? courseID) =>
      (super.noSuchMethod(
            Invocation.method(#removeCoursePersonalDesign, [courseID]),
            returnValue: _i10.Future<bool>.value(false),
            returnValueForMissingStub: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<_i5.AppFunctionsResult<bool>> memberUpdateRole({
    required String? courseID,
    required String? newMemberID,
    required _i4.MemberRole? newRole,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#memberUpdateRole, [], {
              #courseID: courseID,
              #newMemberID: newMemberID,
              #newRole: newRole,
            }),
            returnValue: _i10.Future<_i5.AppFunctionsResult<bool>>.value(
              _FakeAppFunctionsResult_3<bool>(
                this,
                Invocation.method(#memberUpdateRole, [], {
                  #courseID: courseID,
                  #newMemberID: newMemberID,
                  #newRole: newRole,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i10.Future<_i5.AppFunctionsResult<bool>>.value(
                  _FakeAppFunctionsResult_3<bool>(
                    this,
                    Invocation.method(#memberUpdateRole, [], {
                      #courseID: courseID,
                      #newMemberID: newMemberID,
                      #newRole: newRole,
                    }),
                  ),
                ),
          )
          as _i10.Future<_i5.AppFunctionsResult<bool>>);

  @override
  _i4.MemberRole? getRoleFromCourseNoSync(String? courseID) =>
      (super.noSuchMethod(
            Invocation.method(#getRoleFromCourseNoSync, [courseID]),
            returnValueForMissingStub: null,
          )
          as _i4.MemberRole?);

  @override
  _i10.Stream<_i4.Course?> streamCourse(String? courseID) =>
      (super.noSuchMethod(
            Invocation.method(#streamCourse, [courseID]),
            returnValue: _i10.Stream<_i4.Course?>.empty(),
            returnValueForMissingStub: _i10.Stream<_i4.Course?>.empty(),
          )
          as _i10.Stream<_i4.Course?>);

  @override
  _i10.Stream<List<_i4.Course>> streamCourses() =>
      (super.noSuchMethod(
            Invocation.method(#streamCourses, []),
            returnValue: _i10.Stream<List<_i4.Course>>.empty(),
            returnValueForMissingStub: _i10.Stream<List<_i4.Course>>.empty(),
          )
          as _i10.Stream<List<_i4.Course>>);

  @override
  _i10.Stream<Map<String, _i4.GroupInfo>> getGroupInfoStream(
    _i12.SchoolClassGateway? schoolClassGateway,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getGroupInfoStream, [schoolClassGateway]),
            returnValue: _i10.Stream<Map<String, _i4.GroupInfo>>.empty(),
            returnValueForMissingStub:
                _i10.Stream<Map<String, _i4.GroupInfo>>.empty(),
          )
          as _i10.Stream<Map<String, _i4.GroupInfo>>);

  @override
  _i10.Future<List<_i4.Course>> getCourses() =>
      (super.noSuchMethod(
            Invocation.method(#getCourses, []),
            returnValue: _i10.Future<List<_i4.Course>>.value(<_i4.Course>[]),
            returnValueForMissingStub: _i10.Future<List<_i4.Course>>.value(
              <_i4.Course>[],
            ),
          )
          as _i10.Future<List<_i4.Course>>);

  @override
  List<_i4.Course> getCurrentCourses() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentCourses, []),
            returnValue: <_i4.Course>[],
            returnValueForMissingStub: <_i4.Course>[],
          )
          as List<_i4.Course>);

  @override
  _i6.CourseId generateCourseId() =>
      (super.noSuchMethod(
            Invocation.method(#generateCourseId, []),
            returnValue: _FakeCourseId_4(
              this,
              Invocation.method(#generateCourseId, []),
            ),
            returnValueForMissingStub: _FakeCourseId_4(
              this,
              Invocation.method(#generateCourseId, []),
            ),
          )
          as _i6.CourseId);

  @override
  bool canEditCourse(_i4.Course? course) =>
      (super.noSuchMethod(
            Invocation.method(#canEditCourse, [course]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);
}
