// Mocks generated by Mockito 5.4.2 from annotations
// in sharezone/test_goldens/settings/support/support_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:ui' as _i6;

import 'package:clock/clock.dart' as _i3;
import 'package:key_value_store/key_value_store.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sharezone/sharezone_plus/subscription_service/subscription_flag.dart'
    as _i4;
import 'package:sharezone/sharezone_plus/subscription_service/subscription_service.dart'
    as _i7;
import 'package:sharezone/support/support_page_controller.dart' as _i5;
import 'package:user/user.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeKeyValueStore_0 extends _i1.SmartFake implements _i2.KeyValueStore {
  _FakeKeyValueStore_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClock_1 extends _i1.SmartFake implements _i3.Clock {
  _FakeClock_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSubscriptionEnabledFlag_2 extends _i1.SmartFake
    implements _i4.SubscriptionEnabledFlag {
  _FakeSubscriptionEnabledFlag_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SupportPageController].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupportPageController extends _i1.Mock
    implements _i5.SupportPageController {
  @override
  bool get isUserSignedIn => (super.noSuchMethod(
        Invocation.getter(#isUserSignedIn),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  set isUserSignedIn(bool? _isUserSignedIn) => super.noSuchMethod(
        Invocation.setter(
          #isUserSignedIn,
          _isUserSignedIn,
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SubscriptionEnabledFlag].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubscriptionEnabledFlag extends _i1.Mock
    implements _i4.SubscriptionEnabledFlag {
  @override
  _i2.KeyValueStore get keyValueStore => (super.noSuchMethod(
        Invocation.getter(#keyValueStore),
        returnValue: _FakeKeyValueStore_0(
          this,
          Invocation.getter(#keyValueStore),
        ),
        returnValueForMissingStub: _FakeKeyValueStore_0(
          this,
          Invocation.getter(#keyValueStore),
        ),
      ) as _i2.KeyValueStore);
  @override
  bool get isEnabled => (super.noSuchMethod(
        Invocation.getter(#isEnabled),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  void toggle() => super.noSuchMethod(
        Invocation.method(
          #toggle,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SubscriptionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubscriptionService extends _i1.Mock
    implements _i7.SubscriptionService {
  @override
  _i8.Stream<_i9.AppUser?> get user => (super.noSuchMethod(
        Invocation.getter(#user),
        returnValue: _i8.Stream<_i9.AppUser?>.empty(),
        returnValueForMissingStub: _i8.Stream<_i9.AppUser?>.empty(),
      ) as _i8.Stream<_i9.AppUser?>);
  @override
  _i3.Clock get clock => (super.noSuchMethod(
        Invocation.getter(#clock),
        returnValue: _FakeClock_1(
          this,
          Invocation.getter(#clock),
        ),
        returnValueForMissingStub: _FakeClock_1(
          this,
          Invocation.getter(#clock),
        ),
      ) as _i3.Clock);
  @override
  _i4.SubscriptionEnabledFlag get isSubscriptionEnabledFlag =>
      (super.noSuchMethod(
        Invocation.getter(#isSubscriptionEnabledFlag),
        returnValue: _FakeSubscriptionEnabledFlag_2(
          this,
          Invocation.getter(#isSubscriptionEnabledFlag),
        ),
        returnValueForMissingStub: _FakeSubscriptionEnabledFlag_2(
          this,
          Invocation.getter(#isSubscriptionEnabledFlag),
        ),
      ) as _i4.SubscriptionEnabledFlag);
  @override
  bool isSubscriptionActive([_i9.AppUser? appUser]) => (super.noSuchMethod(
        Invocation.method(
          #isSubscriptionActive,
          [appUser],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  _i8.Stream<bool> isSubscriptionActiveStream() => (super.noSuchMethod(
        Invocation.method(
          #isSubscriptionActiveStream,
          [],
        ),
        returnValue: _i8.Stream<bool>.empty(),
        returnValueForMissingStub: _i8.Stream<bool>.empty(),
      ) as _i8.Stream<bool>);
  @override
  bool hasFeatureUnlocked(_i7.SharezonePlusFeature? feature) =>
      (super.noSuchMethod(
        Invocation.method(
          #hasFeatureUnlocked,
          [feature],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
}
