// Mocks generated by Mockito 5.4.6 from annotations
// in sharezone/test/grades/pages/subjects_page/subjects_page_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:flutter/material.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sharezone/grades/pages/subjects_page/subjects_page_controller.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeBuildContext_0 extends _i1.SmartFake implements _i2.BuildContext {
  _FakeBuildContext_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SubjectsPageControllerTranslations].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubjectsPageControllerTranslations extends _i1.Mock
    implements _i3.SubjectsPageControllerTranslations {
  @override
  _i2.BuildContext get context =>
      (super.noSuchMethod(
            Invocation.getter(#context),
            returnValue: _FakeBuildContext_0(this, Invocation.getter(#context)),
            returnValueForMissingStub: _FakeBuildContext_0(
              this,
              Invocation.getter(#context),
            ),
          )
          as _i2.BuildContext);
}
