// Mocks generated by Mockito 5.4.4 from annotations
// in sharezone/test_goldens/grades/pages/grade_details_page/grade_details_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:ui' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:sharezone/grades/pages/grades_details_page/grade_details_page_controller.dart'
    as _i3;
import 'package:sharezone/grades/pages/grades_details_page/grade_details_page_controller_factory.dart'
    as _i6;
import 'package:sharezone/grades/pages/shared/saved_grade_id.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSavedGradeId_0 extends _i1.SmartFake implements _i2.SavedGradeId {
  _FakeSavedGradeId_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGradeDetailsPageController_1 extends _i1.SmartFake
    implements _i3.GradeDetailsPageController {
  _FakeGradeDetailsPageController_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GradeDetailsPageController].
///
/// See the documentation for Mockito's code generation for more information.
class MockGradeDetailsPageController extends _i1.Mock
    implements _i3.GradeDetailsPageController {
  @override
  _i2.SavedGradeId get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _FakeSavedGradeId_0(
          this,
          Invocation.getter(#id),
        ),
        returnValueForMissingStub: _FakeSavedGradeId_0(
          this,
          Invocation.getter(#id),
        ),
      ) as _i2.SavedGradeId);
  @override
  _i3.GradeDetailsPageState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _i4.dummyValue<_i3.GradeDetailsPageState>(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _i4.dummyValue<_i3.GradeDetailsPageState>(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.GradeDetailsPageState);
  @override
  set state(_i3.GradeDetailsPageState? _state) => super.noSuchMethod(
        Invocation.setter(
          #state,
          _state,
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  void deleteGrade() => super.noSuchMethod(
        Invocation.method(
          #deleteGrade,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [GradeDetailsPageControllerFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockGradeDetailsPageControllerFactory extends _i1.Mock
    implements _i6.GradeDetailsPageControllerFactory {
  @override
  _i3.GradeDetailsPageController create(_i2.SavedGradeId? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [id],
        ),
        returnValue: _FakeGradeDetailsPageController_1(
          this,
          Invocation.method(
            #create,
            [id],
          ),
        ),
        returnValueForMissingStub: _FakeGradeDetailsPageController_1(
          this,
          Invocation.method(
            #create,
            [id],
          ),
        ),
      ) as _i3.GradeDetailsPageController);
}
