# Copyright (c) 2022 Sharezone UG (haftungsbeschränkt)
# Licensed under the EUPL-1.2-or-later.
#
# You may obtain a copy of the Licence at:
# https://joinup.ec.europa.eu/software/page/eupl
#
# SPDX-License-Identifier: EUPL-1.2

# A workaround for GitHub Actions jobs that required and based on a path.
#
# Currently, it's not possible to set a GitHub Action to required which is
# based on path changes. The reason for this that the action is not executed
# when the action does not match the paths. Therefore, merging will be
# blocked.
#
# A workaround is to have a job which the same name. 
#
# https://github.com/github/docs/commit/4364076e0fb56c2579ae90cd048939eaa2c18954

name: cli-fallback-ci

on:
  merge_group:
    types:
      - checks_requested
    # For fallback CIs we don't need to add the paths-ignore because it's no
    # harm when the fallback checks being executed.
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths-ignore:
      - ".fvm/fvm_config.json"
      - "tools/sz_repo_cli/**"
      - ".github/workflows/app_ci.yml"
      - '!**.md'
      - '!**.mdx'
      - '!**.gitignore'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No test required"'

  analyze:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No analyze required"'
