# Copyright (c) 2022 Sharezone UG (haftungsbeschränkt)
# Licensed under the EUPL-1.2-or-later.
#
# You may obtain a copy of the Licence at:
# https://joinup.ec.europa.eu/software/page/eupl
#
# SPDX-License-Identifier: EUPL-1.2

# A workaround for GitHub Actions jobs that required and based on a path.
#
# Currently, it's not possible to set a GitHub Action to required which is
# based on path changes. The reason for this that the action is not executed
# when the action does not match the paths. Therefore, merging will be
# blocked.
#
# A workaround is to have a job which the same name.
#
# https://github.com/github/docs/commit/4364076e0fb56c2579ae90cd048939eaa2c18954

name: integration-tests-app-fallback-ci

on:
  pull_request:

jobs:
  android-integration-test:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No android-integration-test required"'

  ios-integration-test:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No ios-integration-test required"'

  macos-build-test:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No web-preview required"'
