name: CI

on:
  pull_request_target:

jobs:
  # This workflow applies labels to pull requests based on the paths that are
  # modified in the pull request.
  #
  # Edit `.github/labeler.yml` to configure labels.
  #
  # For more information, see: https://github.com/actions/labeler
  test-1:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3