# Copyright (c) 2022 Sharezone UG (haftungsbeschränkt)
# Licensed under the EUPL-1.2-or-later.
#
# You may obtain a copy of the Licence at:
# https://joinup.ec.europa.eu/software/page/eupl
#
# SPDX-License-Identifier: EUPL-1.2

name: website-cd

on:
  push:
    branches:
      - main
  pull_request:
    
jobs:
  deploy:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        environment:
          - name: dev
            projectId: sharezone-debug
            serviceAccountSecret: FIREBASE_SERVICE_ACCOUNT_SHAREZONE_DEBUG
          # - name: prod
          #   projectId: sharezone-c2bd8
          #   serviceAccountSecret: FIREBASE_HOSTING_PROD_KEY
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Set Flutter version from FVM config file to environment variables
        uses: kuhnroyal/flutter-fvm-config-action@6ffa30473b346f7d7c63cf9e03e6a886f940a72b

      - uses: subosito/flutter-action@2783a3f08e1baf891508463f8c6653c258246225
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}

      - name: Build
        working-directory: website
        run: |
          # We use the canvaskit renderer because the html renderer is a bit
          # buggy.
          flutter build web \
            --web-renderer canvaskit

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets[matrix.environment.serviceAccountSecret] }}'
          channelId: live
          entryPoint: website/build/web
          projectId: ${{ matrix.environment.projectId }}
